/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.helmo.gbeditor;

import javafx.application.Application;
import javafx.stage.Stage;
import org.helmo.gbeditor.controller.AuthController;
import org.helmo.gbeditor.model.AuthServices;
import org.helmo.gbeditor.views.AuthView;

public class App extends Application {
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) {
        AuthController authController = new AuthController(new AuthServices());
        AuthView authView = new AuthView(authController);
        authView.display(primaryStage);
        primaryStage.setTitle("GB Editor");
    }
}
